### ISSUE TITLE
Consider switching to `Finch` HTTP client

### ISSUE THREAD

**Issue by balexand** [robottokauf3/meilisearch-elixir#12]
Thanks for creating this awesome library. Would you consider switching the HTTP client from httpoison to finch? Reasons include:

- Finch works better in high throughput scenarios. Using Meilisearch for search as you type can definitely become high throughput. See [this post](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) on the Elixir Forum for details. 
- Finch is very popular in the Elixir community. It will even be a default dependency in the next release of Phoenix (https://github.com/phoenixframework/phoenix/issues/4876).
- I've personally been bitten by this serious bug in hackney (which httpoison is based on) which crashes the process that calls httpoison. It's quite serious and still unresolved 4 years later despite being the most upvoted issue in hackney. https://github.com/benoitc/hackney/issues/464

If you're open to this then I'd be happy to submit a pull-request updating the `Meilisearch.HTTP` to use Finch. Thanks.

**Comment by Calamari** [comment]
Hey @balexand. The current master now contains a version that uses Finch. Check this out, and if you got further great feedback. I am all ears :-)

**Comment by balexand** [comment]
Awesome, thank you!
