### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by gargakshit** [robottokauf3/meilisearch-elixir#3]
I see no commits since September, and no-one is replying to #2. So I wanted to know if it is still maintained, and is it stable enough to be used in prod?

**Comment by robottokauf3** [comment]
Yup, I took some time away from my public projects to focus on work and life.  I've been running the v0.18_updates branch in prod for about 6 months without issue.

I'm feeling refreshed and plan to pick the project up again over the next few weeks to release a 1.x version on hex.pm.
