### ISSUE TITLE
Docs Refer to incorrect module domains

### ISSUE THREAD

**Issue by mazz** [robottokauf3/meilisearch-elixir#5]
Meilisearch.Index => Meilisearch.Indexes
Meilisearch.Document => Meilisearch.Documents

There may be more ..

**Comment by robottokauf3** [comment]
Good catch. I'll go through this weekend and see where I missed updating the docs when renaming the modules.

**Comment by oshosanya** [comment]
@robottokauf3 Would you welcome a pull request to fix these issues in the docs? I just fell victim to it too.

**Comment by robottokauf3** [comment]
Updated
